[package]
name = "wirefart_ip"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
wirefart_test = { path = "../wirefart_test" }
