[package]
name = "wirefart_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wirefart_tun = { path = "../wirefart_tun" }
wirefart_ip = { path = "../wirefart_ip" }
